using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IM.Service.Company.Data.Migrations
{
    public partial class InsertToCompanySources : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "CompanySources",
                columns: new[] { "CompanyId", "SourceId", "Value" },
                values: new object[,]
                {
                    {"AAPL"  ,(byte)3,   "AAPL"}
                    ,{"AAPL"  ,(byte)4,   "apple-computer-inc"}
                    ,{"ABT"   ,(byte)3,   "ABT"}
                    ,{"ABT"   ,(byte)4,   "abbott-laboratories"}
                    ,{"ADBE"  ,(byte)3,   "ADBE"}
                    ,{"ADBE"  ,(byte)4,   "adobe-sys-inc"}
                    ,{"AKRN"  ,(byte)2,   "AKRN"}
                    ,{"AKRN"  ,(byte)4,   "akron_rts"}
                    ,{"ALGN"  ,(byte)3,   "ALGN"}
                    ,{"ALGN"  ,(byte)4,   "align-technology"}
                    ,{"ALRS"  ,(byte)2,   "ALRS"}
                    ,{"ALRS"  ,(byte)4,   "alrosa-ao"}
                    ,{"AMAT"  ,(byte)3,   "AMAT"}
                    ,{"AMAT"  ,(byte)4,   "applied-matls-inc"}
                    ,{"AMZN"  ,(byte)3,   "AMZN"}
                    ,{"AMZN"  ,(byte)4,   "amazon-com-inc"}
                    ,{"APD"   ,(byte)3,   "APD"}
                    ,{"APD"   ,(byte)4,   "air-prods---chem"}
                    ,{"AXP"   ,(byte)3,   "AXP"}
                    ,{"AXP"   ,(byte)4,   "american-express"}
                    ,{"BA"    ,(byte)3,   "BA"}
                    ,{"BA"    ,(byte)4,   "boeing-co"}
                    ,{"BABA"  ,(byte)3,   "BABA"}
                    ,{"BABA"  ,(byte)4,   "alibaba"}
                    ,{"BAC"   ,(byte)3,   "BAC"}
                    ,{"BAC"   ,(byte)4,   "bank-of-america"}
                    ,{"BBY"   ,(byte)3,   "BBY"}
                    ,{"BBY"   ,(byte)4,   "best-buy"}
                    ,{"BDX"   ,(byte)3,   "BDX"}
                    ,{"BDX"   ,(byte)4,   "becton-dickinsn"}
                    ,{"BIIB"  ,(byte)3,   "BIIB"}
                    ,{"BIIB"  ,(byte)4,   "biogen-idec-inc"}
                    ,{"BSX"   ,(byte)3,   "BSX"}
                    ,{"BSX"   ,(byte)4,   "boston-scien-cp"}
                    ,{"CBOM"  ,(byte)2,   "CBOM"}
                    ,{"CBOM"  ,(byte)4,   "moskovskiy-kreditnyi-bank-oao"}
                    ,{"CCL"   ,(byte)3,   "CCL"}
                    ,{"CCL"   ,(byte)4,   "carnival-corp-exch"}
                    ,{"CHMF"  ,(byte)2,   "CHMF"}
                    ,{"CHMF"  ,(byte)4,   "severstal_rts"}
                    ,{"CHMK"  ,(byte)2,   "CHMK"}
                    ,{"CHMK"  ,(byte)4,   "chmk"}
                    ,{"CHTR"  ,(byte)3,   "CHTR"}
                    ,{"CHTR"  ,(byte)4,   "charter-communications"}
                    ,{"CMCSA" ,(byte)3,   "CMCSA"}
                    ,{"CMCSA" ,(byte)4,   "comcast-corp-new"}
                    ,{"CMI"   ,(byte)3,   "CMI"}
                    ,{"CMI"   ,(byte)4,   "cummins-inc"}
                    ,{"COP"   ,(byte)3,   "COP"}
                    ,{"COP"   ,(byte)4,   "conoco-phillips"}
                    ,{"CRM"   ,(byte)3,   "CRM"}
                    ,{"CRM"   ,(byte)4,   "salesforce-com"}
                    ,{"CSCO"  ,(byte)3,   "CSCO"}
                    ,{"CSCO"  ,(byte)4,   "cisco-sys-inc"}
                    ,{"CVX"   ,(byte)3,   "CVX"}
                    ,{"CVX"   ,(byte)4,   "chevron"}
                    ,{"D" ,(byte)3,   "D"}
                    ,{"D" ,(byte)4,   "dominion-res"}
                    ,{"DHR"   ,(byte)3,   "DHR"}
                    ,{"DHR"   ,(byte)4,   "danaher-corp"}
                    ,{"DIS"   ,(byte)3,   "DIS"}
                    ,{"DIS"   ,(byte)4,   "disney"}
                    ,{"DISCK" ,(byte)3,   "DISCK"}
                    ,{"DISCK" ,(byte)4,   "discovery-holding-co"}
                    ,{"DOV"   ,(byte)3,   "DOV"}
                    ,{"DOV"   ,(byte)4,   "dover-corp"}
                    ,{"DSKY"  ,(byte)2,   "DSKY"}
                    ,{"DSKY"  ,(byte)4,   "detskiy-mir-pao"}
                    ,{"EMR"   ,(byte)3,   "EMR"}
                    ,{"EMR"   ,(byte)4,   "emerson-elec"}
                    ,{"ENRU"  ,(byte)2,   "ENRU"}
                    ,{"ENRU"  ,(byte)4,   "ogk-5"}
                    ,{"F" ,(byte)3,   "F"}
                    ,{"F" ,(byte)4,   "ford-motor-co"}
                    ,{"FB"    ,(byte)3,   "FB"}
                    ,{"FB"    ,(byte)4,   "facebook-inc"}
                    ,{"FIS"   ,(byte)3,   "FIS"}
                    ,{"FIS"   ,(byte)4,   "fidelity-natl-in"}
                    ,{"FIVE"  ,(byte)2,   "FIVE"}
                    ,{"FIVE"  ,(byte)4,   "x5-retail-grp"}
                    ,{"GAZP"  ,(byte)2,   "GAZP"}
                    ,{"GAZP"  ,(byte)4,   "gazprom_rts"}
                    ,{"GE"    ,(byte)3,   "GE"}
                    ,{"GE"    ,(byte)4,   "general-electric"}
                    ,{"GIS"   ,(byte)3,   "GIS"}
                    ,{"GIS"   ,(byte)4,   "general-mills"}
                    ,{"GMKN"  ,(byte)2,   "GMKN"}
                    ,{"GMKN"  ,(byte)4,   "gmk-noril-nickel_rts"}
                    ,{"GOOG"  ,(byte)3,   "GOOG"}
                    ,{"GOOG"  ,(byte)4,   "google-inc"}
                    ,{"GPN"   ,(byte)3,   "GPN"}
                    ,{"GPN"   ,(byte)4,   "global-payments"}
                    ,{"HON"   ,(byte)3,   "HON"}
                    ,{"HON"   ,(byte)4,   "honeywell-intl"}
                    ,{"HPQ"   ,(byte)3,   "HPQ"}
                    ,{"HPQ"   ,(byte)4,   "hewlett-pack"}
                    ,{"HYDR"  ,(byte)2,   "HYDR"}
                    ,{"HYDR"  ,(byte)4,   "gidroogk-011d"}
                    ,{"IBM"   ,(byte)3,   "IBM"}
                    ,{"IBM"   ,(byte)4,   "ibm"}
                    ,{"ILMN"  ,(byte)3,   "ILMN"}
                    ,{"ILMN"  ,(byte)4,   "illumina,-inc."}
                    ,{"INTC"  ,(byte)3,   "INTC"}
                    ,{"INTC"  ,(byte)4,   "intel-corp"}
                    ,{"IRKT"  ,(byte)2,   "IRKT"}
                    ,{"IRKT"  ,(byte)4,   "irkut-corp"}
                    ,{"ISKJ"  ,(byte)2,   "ISKJ"}
                    ,{"ISKJ"  ,(byte)4,   "human-stem-cells-institute"}
                    ,{"JNJ"   ,(byte)3,   "JNJ"}
                    ,{"JNJ"   ,(byte)4,   "johnson-johnson"}
                    ,{"KAZT"  ,(byte)2,   "KAZT"}
                    ,{"KAZT"  ,(byte)4,   "kuibyshevazot"}
                    ,{"KDP"   ,(byte)3,   "KDP"}
                    ,{"KDP"   ,(byte)4,   "dr-pepper-snapple"}
                    ,{"KHC"   ,(byte)3,   "KHC"}
                    ,{"KHC"   ,(byte)4,   "kraft-foods-inc"}
                    ,{"KMAZ"  ,(byte)2,   "KMAZ"}
                    ,{"KMAZ"  ,(byte)4,   "kamaz"}
                    ,{"KMI"   ,(byte)3,   "KMI"}
                    ,{"KMI"   ,(byte)4,   "kinder-morgan"}
                    ,{"KO"    ,(byte)3,   "KO"}
                    ,{"KO"    ,(byte)4,   "coca-cola-co"}
                    ,{"LKOH"  ,(byte)2,   "LKOH"}
                    ,{"LKOH"  ,(byte)4,   "lukoil_rts"}
                    ,{"LMT"   ,(byte)3,   "LMT"}
                    ,{"LMT"   ,(byte)4,   "lockheed-martin"}
                    ,{"LNTA"  ,(byte)2,   "LNTA"}
                    ,{"LNTA"  ,(byte)4,   "lenta-ltd"}
                    ,{"LNZL"  ,(byte)2,   "LNZL"}
                    ,{"LNZL"  ,(byte)4,   "lenzoloto-oao"}
                    ,{"LRCX"  ,(byte)3,   "LRCX"}
                    ,{"LRCX"  ,(byte)4,   "lam-research-corp"}
                    ,{"LUV"   ,(byte)3,   "LUV"}
                    ,{"LUV"   ,(byte)4,   "sth-west-airlines"}
                    ,{"LVHK"  ,(byte)2,   "LVHK"}
                    ,{"LVHK"  ,(byte)4,   "levenguk-oao"}
                    ,{"LYV"   ,(byte)3,   "LYV"}
                    ,{"LYV"   ,(byte)4,   "live-nation-entertainment-inc"}
                    ,{"MA"    ,(byte)3,   "MA"}
                    ,{"MA"    ,(byte)4,   "mastercard-cl-a"}
                    ,{"MAGN"  ,(byte)2,   "MAGN"}
                    ,{"MAGN"  ,(byte)4,   "mmk_rts"}
                    ,{"MAS"   ,(byte)3,   "MAS"}
                    ,{"MAS"   ,(byte)4,   "masco-corp"}
                    ,{"MCD"   ,(byte)3,   "MCD"}
                    ,{"MCD"   ,(byte)4,   "mcdonalds"}
                    ,{"MDLZ"  ,(byte)3,   "MDLZ"}
                    ,{"MDLZ"  ,(byte)4,   "mondelez-international-inc"}
                    ,{"MDT"   ,(byte)3,   "MDT"}
                    ,{"MDT"   ,(byte)4,   "medtronic"}
                    ,{"MMM"   ,(byte)3,   "MMM"}
                    ,{"MMM"   ,(byte)4,   "3m-co"}
                    ,{"MRK"   ,(byte)3,   "MRK"}
                    ,{"MRK"   ,(byte)4,   "merck---co"}
                    ,{"MRKV"  ,(byte)2,   "MRKV"}
                    ,{"MRKV"  ,(byte)4,   "mrsk-volgi"}
                    ,{"MRNA"  ,(byte)3,   "MRNA"}
                    ,{"MRNA"  ,(byte)4,   "moderna"}
                    ,{"MSFT"  ,(byte)3,   "MSFT"}
                    ,{"MSFT"  ,(byte)4,   "microsoft-corp"}
                    ,{"MSNG"  ,(byte)2,   "MSNG"}
                    ,{"MSNG"  ,(byte)4,   "mosenergo_rts"}
                    ,{"MTLR"  ,(byte)2,   "MTLR"}
                    ,{"MTLR"  ,(byte)4,   "sg-mechel_rts"}
                    ,{"MTSS"  ,(byte)2,   "MTSS"}
                    ,{"MTSS"  ,(byte)4,   "mts_rts"}
                    ,{"MU"    ,(byte)3,   "MU"}
                    ,{"MU"    ,(byte)4,   "micron-tech"}
                    ,{"NCLH"  ,(byte)3,   "NCLH"}
                    ,{"NCLH"  ,(byte)4,   "norwegian-cruise-line-holdings-ltd"}
                    ,{"NEE"   ,(byte)3,   "NEE"}
                    ,{"NEE"   ,(byte)4,   "nextera-energy-inc"}
                    ,{"NEM"   ,(byte)3,   "NEM"}
                    ,{"NEM"   ,(byte)4,   "newmont-mining"}
                    ,{"NFLX"  ,(byte)3,   "NFLX"}
                    ,{"NFLX"  ,(byte)4,   "netflix,-inc."}
                    ,{"NKHP"  ,(byte)2,   "NKHP"}
                    ,{"NKHP"  ,(byte)4,   "nkhp-pao"}
                    ,{"NOC"   ,(byte)3,   "NOC"}
                    ,{"NOC"   ,(byte)4,   "northrop-grumman"}
                    ,{"NRG"   ,(byte)3,   "NRG"}
                    ,{"NRG"   ,(byte)4,   "nrg-energy-inc"}
                    ,{"NVDA"  ,(byte)3,   "NVDA"}
                    ,{"NVDA"  ,(byte)4,   "nvidia-corp"}
                    ,{"NVTK"  ,(byte)2,   "NVTK"}
                    ,{"NVTK"  ,(byte)4,   "novatek_rts"}
                    ,{"OMZZP" ,(byte)2,   "OMZZP"}
                    ,{"OMZZP" ,(byte)4,   "omz-(pref)"}
                    ,{"ORCL"  ,(byte)3,   "ORCL"}
                    ,{"ORCL"  ,(byte)4,   "oracle-corp"}
                    ,{"PANW"  ,(byte)3,   "PANW"}
                    ,{"PANW"  ,(byte)4,   "palo-alto-netwrk"}
                    ,{"PEP"   ,(byte)3,   "PEP"}
                    ,{"PEP"   ,(byte)4,   "pepsico"}
                    ,{"PFE"   ,(byte)3,   "PFE"}
                    ,{"PFE"   ,(byte)4,   "pfizer"}
                    ,{"PH"    ,(byte)3,   "PH"}
                    ,{"PH"    ,(byte)4,   "parkerhannifin"}
                    ,{"PHOR"  ,(byte)2,   "PHOR"}
                    ,{"PHOR"  ,(byte)4,   "phosagro"}
                    ,{"PLZL"  ,(byte)2,   "PLZL"}
                    ,{"PLZL"  ,(byte)4,   "polyus-zoloto_rts"}
                    ,{"POLY"  ,(byte)2,   "POLY"}
                    ,{"PYPL"  ,(byte)3,   "PYPL"}
                    ,{"PYPL"  ,(byte)4,   "paypal-holdings-inc"}
                    ,{"QCOM"  ,(byte)3,   "QCOM"}
                    ,{"QCOM"  ,(byte)4,   "qualcomm-inc"}
                    ,{"RCL"   ,(byte)3,   "RCL"}
                    ,{"RCL"   ,(byte)4,   "royal-caribbean"}
                    ,{"RKKE"  ,(byte)2,   "RKKE"}
                    ,{"RKKE"  ,(byte)4,   "rsc-energia"}
                    ,{"ROSB"  ,(byte)2,   "ROSB"}
                    ,{"ROSB"  ,(byte)4,   "rosbank"}
                    ,{"ROSN"  ,(byte)2,   "ROSN"}
                    ,{"ROSN"  ,(byte)4,   "rosneft_rts"}
                    ,{"RPM"   ,(byte)3,   "RPM"}
                    ,{"RPM"   ,(byte)4,   "rpm-intl-inc"}
                    ,{"RS"    ,(byte)3,   "RS"}
                    ,{"RS"    ,(byte)4,   "reliance-steel---aluminum-co."}
                    ,{"RTKM"  ,(byte)2,   "RTKM"}
                    ,{"RTKM"  ,(byte)4,   "rostelecom"}
                    ,{"RTX"   ,(byte)3,   "RTX"}
                    ,{"RTX"   ,(byte)4,   "united-tech"}
                    ,{"SBER"  ,(byte)2,   "SBER"}
                    ,{"SBER"  ,(byte)4,   "sberbank_rts"}
                    ,{"SCCO"  ,(byte)3,   "SCCO"}
                    ,{"SCCO"  ,(byte)4,   "southern-copper-corp."}
                    ,{"SELG"  ,(byte)2,   "SELG"}
                    ,{"SELG"  ,(byte)4,   "seligdar"}
                    ,{"SHW"   ,(byte)3,   "SHW"}
                    ,{"SHW"   ,(byte)4,   "sherwinwilliams"}
                    ,{"SIRI"  ,(byte)3,   "SIRI"}
                    ,{"SIRI"  ,(byte)4,   "sirius-satellite-radio-inc"}
                    ,{"SNGS"  ,(byte)2,   "SNGS"}
                    ,{"SNGS"  ,(byte)4,   "surgutneftegas_rts"}
                    ,{"SO"    ,(byte)3,   "SO"}
                    ,{"SO"    ,(byte)4,   "southern-co"}
                    ,{"SVAV"  ,(byte)2,   "SVAV"}
                    ,{"SVAV"  ,(byte)4,   "sollers"}
                    ,{"T" ,(byte)3,   "T"}
                    ,{"T" ,(byte)4,   "at-t"}
                    ,{"TCSG"  ,(byte)2,   "TCSG"}
                    ,{"TCSG"  ,(byte)4,   "tcs-group-holding-plc"}
                    ,{"TRMK"  ,(byte)2,   "TRMK"}
                    ,{"TRMK"  ,(byte)4,   "tmk"}
                    ,{"TSLA"  ,(byte)3,   "TSLA"}
                    ,{"TSLA"  ,(byte)4,   "tesla-motors"}
                    ,{"TUZA"  ,(byte)2,   "TUZA"}
                    ,{"TUZA"  ,(byte)4,   "tza-oao"}
                    ,{"TWTR"  ,(byte)3,   "TWTR"}
                    ,{"TWTR"  ,(byte)4,   "twitter-inc"}
                    ,{"UNAC"  ,(byte)2,   "UNAC"}
                    ,{"UNAC"  ,(byte)4,   "united-aircraft-corporation"}
                    ,{"V" ,(byte)3,   "V"}
                    ,{"V" ,(byte)4,   "visa-inc"}
                    ,{"VRTX"  ,(byte)3,   "VRTX"}
                    ,{"VRTX"  ,(byte)4,   "vertex-pharm"}
                    ,{"VTBR"  ,(byte)2,   "VTBR"}
                    ,{"VTBR"  ,(byte)4,   "vtb_rts"}
                    ,{"VZ"    ,(byte)3,   "VZ"}
                    ,{"VZ"    ,(byte)4,   "verizon-communications"}
                    ,{"WFC"   ,(byte)3,   "WFC"}
                    ,{"WFC"   ,(byte)4,   "wells-fargo"}
                    ,{"WM"    ,(byte)3,   "WM"}
                    ,{"WM"    ,(byte)4,   "waste-managemnt"}
                    ,{"YNDX"  ,(byte)2,   "YNDX"}
                    ,{"YNDX"  ,(byte)4,   "yandex"}
                    ,{"YY"    ,(byte)3,   "YY"}
                    ,{"YY"    ,(byte)4,   "yy-inc"}
                    ,{"ZILL"  ,(byte)2,   "ZILL"}
                    ,{"ZILL"  ,(byte)4,   "amo-zil" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
