# @format

version: '3.7'
services:
  postgresql:
    image: postgres:13
    container_name: postgresql
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: paviams
    restart: always
    ports:
      - 5672:5672 #amqp
      - 15672:15672 #http
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      #   - ./volumes/rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      #   - ./volumes/rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@paviams
      - ./volumes/rabbitmq/logs:/var/log/rabbitmq/log
  # traefik:
  #   image: traefik:v2.0
  #   container_name: traefik
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./volumes/traefik/traefik.yml:/etc/traefik/traefik.yml
  #   depends_on:
  #     - gateways_web_companies

  gateways_web_companies:
    container_name: gateways_web_companies
    build: ./Gateways/Web/IM.Gateways.Web.Companies.Api/
    # restart: always
    ports:
      - 2101:2101
      # - 21011:21011
    environment:
      - ASPNETCORE_URLS=http://+:2101
      # - ASPNETCORE_URLS=https://+:21011;http://+:2101
      - ConnectionString=Server=postgresql;Port=5432;Database=CompanyGateways;UserId=postgres;Password=${DB_PASSWORD}
    depends_on:
      - services_companies_prices
      - services_companies_reports
      - services_analyzer
  services_companies_prices:
    container_name: services_companies_prices
    build: ./Services/Companies/IM.Services.Companies.Prices.Api/
    # restart: always
    ports:
      - 3101:3101
    environment:
      - ASPNETCORE_URLS=http://+:3101
      - ConnectionString=Server=postgresql;Port=5432;Database=CompanyPrices;UserId=postgres;Password=${DB_PASSWORD}
      - ServiceSettings__TdAmeritradeSettings__ApiKey=${DTAMERITRADE_APIKEY}
    depends_on:
      - postgresql
      - rabbitmq
  services_companies_reports:
    container_name: services_companies_reports
    build: ./Services/Companies/IM.Services.Companies.Reports.Api/
    # restart: always
    ports:
      - 3102:3102
    environment:
      - ASPNETCORE_URLS=http://+:3102
      - ConnectionString=Server=postgresql;Port=5432;Database=CompanyReports;UserId=postgres;Password=${DB_PASSWORD}
    depends_on:
      - postgresql
      - rabbitmq
  services_analyzer:
    container_name: services_analyzer
    build: ./Services/IM.Services.Analyzer.Api/
    # restart: always
    ports:
      - 3200:3200
    environment:
      - ASPNETCORE_URLS=http://+:3200
      - ConnectionString=Server=postgresql;Port=5432;Database=Analyzer;UserId=postgres;Password=${DB_PASSWORD}
    depends_on:
      - postgresql
      - rabbitmq
