// <auto-generated />
using System;
using IM.Service.Company.Prices.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace IM.Service.Company.Prices.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211009120138_AddToTickerFieldSourceValue")]
    partial class AddToTickerFieldSourceValue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("IM.Service.Company.Prices.DataAccess.Entities.Price", b =>
                {
                    b.Property<string>("TickerName")
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("TickerName", "Date");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("IM.Service.Company.Prices.DataAccess.Entities.SourceType", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SourceTypes");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Select price source"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "moex"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "tdameritrade"
                        });
                });

            modelBuilder.Entity("IM.Service.Company.Prices.DataAccess.Entities.Ticker", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<byte>("SourceTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceValue")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Name");

                    b.HasIndex("SourceTypeId");

                    b.ToTable("Tickers");
                });

            modelBuilder.Entity("IM.Service.Company.Prices.DataAccess.Entities.Price", b =>
                {
                    b.HasOne("IM.Service.Company.Prices.DataAccess.Entities.Ticker", "Ticker")
                        .WithMany("Prices")
                        .HasForeignKey("TickerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("IM.Service.Company.Prices.DataAccess.Entities.Ticker", b =>
                {
                    b.HasOne("IM.Service.Company.Prices.DataAccess.Entities.SourceType", "SourceType")
                        .WithMany("Tickers")
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceType");
                });

            modelBuilder.Entity("IM.Service.Company.Prices.DataAccess.Entities.SourceType", b =>
                {
                    b.Navigation("Tickers");
                });

            modelBuilder.Entity("IM.Service.Company.Prices.DataAccess.Entities.Ticker", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
